
version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=blogs_api
