version: '3.9'
services:
  backend:
    image: node:16-alpine
    command: npm run dev
    restart: on-failure
    working_dir: /app/backend
    volumes:
      - .:/app/backend
    ports:
      - 3001:${BACK_PORT}
    tty: true
    stdin_open: true
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - BACK_PORT=${BACK_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=mongo
      - DB_NAME=${DB_NAME}
      - DB_PORT=27017
      - DATABASE_URL=mongodb://mongo:27017/${DB_NAME}
  mongo:
    image: mongo:5.0.9
    restart: always
    ports:
      - ${DB_PORT}:27017
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      # MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      timeout: 15s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
