CREATE DATABASE IF NOT EXISTS cep_lookup;
DROP TABLE IF EXISTS ceps;
USE cep_lookup;

CREATE TABLE IF NOT EXISTS ceps (
  cep VARCHAR(9) NOT NULL PRIMARY KEY,
  logradouro VARCHAR(50) NOT NULL,
  bairro VARCHAR(20) NOT NULL,
  localidade VARCHAR(20) NOT NULL,
  uf VARCHAR(2) NOT NULL
);
